version: '2'
services:
  postgres:
      image: postgres:13
      container_name: postgres
      environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASS}
          - POSTGRES_DB=airflow
      network_mode: host

  airflow-newspipe:
    build: 
      context: airflow-newspipe-docker/
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASS=${POSTGRES_PASS}
        - POSTGRES_IP=127.0.0.1
    container_name: airflow_newspipe
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/airflow/dags
      - ./output:/output
      - ./logs:/airflow/logs
    environment:
      - MONGO_ROOT_USER=${MONGO_ROOT_USER}
      - MONGO_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_DATABASE_NAME=NewsPipe
    depends_on:
      - "postgres"
      - "mongo"
    restart: always
    network_mode: host

  mongo:
    image: mongo:4.2-bionic
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=NewsPipe
    network_mode: host
    volumes:
      - ./mongodata:/data
    command: --bind_ip=127.0.0.1

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo_express
    environment:
      - ME_CONFIG_MONGODB_SERVER=127.0.0.1
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - "mongo"
    restart: always
    network_mode: host

  mongo-charts:
    image: quay.io/mongodb/charts:v0.11.0
    container_name: mongo_charts
    volumes:
      - ./mongo_charts:/mongodb-charts/volumes
    environment:
      CHARTS_SUPPORT_WIDGET_AND_METRICS: "on"
      CHARTS_MONGODB_URI: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@localhost:27017
    depends_on:
      - "mongo"
    restart: always
    network_mode: host

  mongo-charts-nginx:
    image: quay.io/dtan4/nginx-basic-auth-proxy:latest
    container_name: mongo_charts_nginx_container
    ports:
      - 8082:80
    environment:
      - BASIC_AUTH_USERNAME=${MONGO_CHART_USERNAME}
      - BASIC_AUTH_PASSWORD=${MONGO_CHART_PASSWORD}
      - PROXY_PASS=http://localhost:80
    depends_on:
      - "mongo-charts"
    network_mode: host
    restart: always
